### ISSUE TITLE
errors when setting properties on class that extends python class

### ISSUE THREAD

**Issue by sigmaSd** [denosaurs/deno_python#54]
```ts
import { python } from "https://deno.land/x/python@0.4.1/mod.ts";

const gi = python.import("gi");
gi.require_version("Gtk", "4.0");
const Gtk = python.import("gi.repository.Gtk");

class MainWindow extends Gtk.ApplicationWindow {
  constructor() {
    super();
    this.a = 4; // error here
  }
}
console.log(new MainWindow());
```

```
error: Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'a'
    this.a = 4;
          ^
    at new MainWindow (file:///home/mrcool/dev/deno/lab/b.ts:10:11)
    at file:///home/mrcool/dev/deno/lab/b.ts:14:13
```

more info here https://github.com/denosaurs/deno_python/issues/53#issuecomment-1797864483

**Comment by sigmaSd** [comment]
using private variables instead , makes it work
```ts
import { python } from "https://deno.land/x/python@0.4.1/mod.ts";

const gi = python.import("gi");
gi.require_version("Gtk", "4.0");
const Gtk = python.import("gi.repository.Gtk");

class MainWindow extends Gtk.ApplicationWindow {
 #a;
  constructor() {
    super();
    this.#a = 4; // no error
  }
}
console.log(new MainWindow());
```

**Comment by sigmaSd** [comment]
I'm "porting" https://github.com/Taiko2k/GTK4PythonTutorial to deno-python and taking note of issues I find along the way here https://github.com/sigmaSd/deno-gtk-py (grep FIXME)

**Comment by sigmaSd** [comment]
Here is a more self contained example
```ts
import { python } from "https://deno.land/x/python@0.4.2/mod.ts";

const m = python.runModule(
  `
class A:
  x = 4
  `,
);

class B extends m.A {
  b;
  constructor() {
    super();
    this.b = 5; // error origin
  }
}

const _b = new B(); // error here
```

This is annoying in practice because it means I can't access any properties/functions of a class from the outside.

I wonder if there is a way to expose an alternative api for the proxy that allows such things.
