### ISSUE TITLE
Numpy example issue

### ISSUE THREAD

**Issue by hoangpq** [denosaurs/deno_python#7]
Thanks for creating deno_python. I tried to run NumPy example but faced this issue.
Could you help me to resolve this issue?

```
error: Uncaught (in promise) PythonError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/local/bin/deno"
  * The NumPy version is: "1.22.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): Symbol not found: _PyBaseObject_Type
  Referenced from: /usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Expected in: flat namespace
 in /usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so

Traceback:
['  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py", line 144, in <module>\n    from . import core\n', '  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>\n    raise ImportError(msg)\n']
  throw new PythonError(errorMessage);
        ^
    at maybeThrowError (https://deno.land/x/python@0.1.0/src/python.ts:641:9)
    at Python.importObject (https://deno.land/x/python@0.1.0/src/python.ts:717:7)
    at Python.import (https://deno.land/x/python@0.1.0/src/python.ts:727:17)
    at file:///Users/hoangpq/WebstormProjects/deno-working/server.ts:3:25
```

But working well on Python REPL

![image](https://user-images.githubusercontent.com/5939997/151330216-e3a92279-99d3-40a1-8fa1-25fc90cef6c0.png)

Environment:
OS: macOS
Python version: 3.8 (Homebrew)
Deno version: 1.18.0

**Comment by DjDeveloperr** [comment]
I suspect it is because we do not set the executable path to the actual Python path, and it is likely trying to call deno as python. However this works for me on Windows. I will try to fix ASAP

**Comment by hoangpq** [comment]
Hi @DjDeveloperr.

Thank you for amazing quick response :)

**Comment by DjDeveloperr** [comment]
Can you try if importing deno_python from `https://raw.githubusercontent.com/denosaurs/deno_python/fix-python-exec/mod.ts` fixes the issue?

**Comment by hoangpq** [comment]
Hi @DjDeveloperr 

It's still happened 

![image](https://user-images.githubusercontent.com/5939997/151332852-2a0ef603-7c9b-4326-b9f6-9b0090b3219c.png)

**Comment by DjDeveloperr** [comment]
Hm, can you send the complete error logged this time?

**Comment by hoangpq** [comment]
Hi @DjDeveloperr.

For sure, here is full stacktrace

```
Download https://raw.githubusercontent.com/denosaurs/deno_python/fix-python-exec/mod.ts
Download https://raw.githubusercontent.com/denosaurs/deno_python/fix-python-exec/src/python.ts
Download https://raw.githubusercontent.com/denosaurs/deno_python/fix-python-exec/src/ffi.ts
Download https://raw.githubusercontent.com/denosaurs/deno_python/fix-python-exec/src/util.ts
Check file:///Users/hoangpq/WebstormProjects/deno-working/server.ts
error: Uncaught (in promise) PythonError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/bin/python3"
  * The NumPy version is: "1.22.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): Symbol not found: _PyBaseObject_Type
  Referenced from: /usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so
  Expected in: flat namespace
 in /usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so

Traceback:
['  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py", line 144, in <module>\n    from . import core\n', '  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>\n    raise ImportError(msg)\n']
  throw new PythonError(errorMessage);
        ^
    at maybeThrowError (https://raw.githubusercontent.com/denosaurs/deno_python/fix-python-exec/src/python.ts:643:9)
    at Python.importObject (https://raw.githubusercontent.com/denosaurs/deno_python/fix-python-exec/src/python.ts:731:7)
    at Python.import (https://raw.githubusercontent.com/denosaurs/deno_python/fix-python-exec/src/python.ts:741:17)
    at file:///Users/hoangpq/WebstormProjects/deno-working/server.ts:3:25
```

**Comment by DjDeveloperr** [comment]
That is quite weird. I will have to debug this locally so I need some more time, sorry 😅

**Comment by hoangpq** [comment]
Thanks @DjDeveloperr.

I did something like this in Nodejs https://github.com/hoangpq/pynode but only in prototype stage,
and quite interesting on your project :)

We can use Python ML lib for Deno. Big thank to you and team.

**Comment by DjDeveloperr** [comment]
So the problem here is NumPy is importing symbols using RTLD_NOW which looks for symbols exported from current process. On unix based systems, this will immediately fail if a symbol is not found in that way. While on Windows, there is nothing like RTLD_NOW and NumPy just opens Python shared library to access those symbols. I will investigate for a possible fix

**Comment by DjDeveloperr** [comment]
So there is only one fix... and it requires a change in Deno itself. We need to pass `RTLD_LAZY | RTLD_GLOBAL` to `dlopen` when loading Python shared library so that it's symbols can be imported from subsequently loaded shared libraries, such as NumPy itself in this case.

**Comment by hoangpq** [comment]
Hi @DjDeveloperr.

Awesome, Thank you for your information 👍

**Comment by DjDeveloperr** [comment]
I've come up with a workaround until Deno supports flags in dlopen, that is to open libc and use dlopen from that in order to pass RTLD_GLOBAL flag. I also added a test case for importing NumPy, CI seems passing on the PR

**Comment by DjDeveloperr** [comment]
Released the fix in 0.1.1

**Comment by hoangpq** [comment]
Awesome new, @DjDeveloperr 👍

**Comment by hoangpq** [comment]
Tested on macOS Big Sur, Python 3.8, Deno 1.18.0, deno_python 0.1.1

![image](https://user-images.githubusercontent.com/5939997/151768874-3a506a19-7b79-4b15-9d90-a86a22c4b59f.png)

Thanks for your help 🥇
